### ISSUE TITLE
Can't run video have Wiseplay 

### ISSUE THREAD

**Issue by s0lut1on** [HMS-Core/hms-wiseplay-demo-exoplayer#1]
Build app with Android Studio Bumblebee 2021

Install app on Cloud Debugging in AppGallery Huawei

Device using is P40 Pro With EMUI 11.0.0 (Minimum require OS support Wiseplay DRM)

Every video can play except Wiseplay video. Is anything else I'm missing when run demo ?

**Comment by s0lut1on** [comment]
And same isssue happen with Wiseplay DRM Demo

**Comment by coolleizhu** [comment]
Can you share the log? Whether the country code of the phone is US(it can be checked in the log)?

**Comment by s0lut1on** [comment]
I run device in CloudDebugging. So I don't have much log to share. Logcat is kind of mess

**Comment by s0lut1on** [comment]
Look like it the error return from app
2022-02-18 09:00:08 1799-1799/? E/EventLogger: internalError [eventTime=245.15, mediaPos=0.00, window=0, loadError
  com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:282)
      at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
      at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487)
      at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288)
      at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
      at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
      at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
      at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      at java.lang.Thread.run(Thread.java:929)
  Caused by: java.net.SocketTimeoutException: failed to connect to drmkit.hwcloudtest.cn/139.9.117.106 (port 8082) from /192.168.1.67 (port 43360) after 8000ms
      at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
      at libcore.io.IoBridge.connect(IoBridge.java:135)
      at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
      at java.net.Socket.connect(Socket.java:621)
      at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
      at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
      at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:439)
      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:280)
      ... 11 more
]

**Comment by coolleizhu** [comment]
It is not suggested to use test Wiseplay service in CloudDebug.

The function is controlled. 

You ip is not in allowlist, so the connection is refused.

You can test in local phone and share us the public IP address of your phone.

You can share it here or create ticket in this address:
https://developer.huawei.com/consumer/en/support/feedback/#/

After adding to allowlist, you will be able to connect to Huawei server.

**Comment by s0lut1on** [comment]
Thank for you comment, I will find device and test it
